import "@styles/globals.css";

import Nav from "@components/Nav";
import { ToastContainer } from 'react-toastify';
import Provider from "@components/Provider";
import 'react-toastify/dist/ReactToastify.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
    <body>
      <Provider>
        <div className='main'>
          <div className='gradient' />
        </div>

        <main className='app'>
          <Nav />
          {children}
        </main>
        <div className="footer" />
        <ToastContainer />
      </Provider>
    </body>
  </html>
  )
}
